# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf71db8324c385d71478b401a08ae49c879c969785ed9dcb24979daae09dca7feda548a83aae9da7ddd622d48c1e82e1f2fa988c019872e1a90d9c7a7318635f

test:
  secret_key_base: 997dcbf678c8fe1bb1963fab2feb02930ebb1dd50fb316e0199cacb6c0ddcd22022727850cf8953acda8d1513460ef5bd9811d7e7c34420813dfecbbba271dc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
